# Generated by Django 3.1.4 on 2021-04-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlmanager', '0002_auto_20210416_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='html',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='project',
        ),
        migrations.DeleteModel(
            name='HtmlFile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
