# Generated by Django 3.1.4 on 2021-04-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlmanager', '0005_project_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
