# Generated by Django 3.1.4 on 2021-04-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlmanager', '0007_remove_projectfile_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='pageno',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='filename',
            field=models.CharField(default='', max_length=80),
        ),
    ]
