# Generated by Django 3.1.4 on 2021-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlmanager', '0008_auto_20210416_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.URLField(default='/project/'),
        ),
    ]
