# Generated by Django 3.1.4 on 2021-04-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlmanager', '0009_project_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='site',
        ),
    ]
